# Generated by Django 3.1.1 on 2020-12-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatoin', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racer_name', models.CharField(max_length=50)),
                ('Introduction', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=20)),
                ('ID_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racer.group')),
            ],
        ),
        migrations.CreateModel(
            name='round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_round', models.CharField(max_length=20)),
                ('ID_Match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racer.match')),
            ],
        ),
        migrations.CreateModel(
            name='Racing_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_type', models.CharField(choices=[('M', 'motorcycle'), ('ort', 'Off road truck'), ('SUV', 'offroad racing')], max_length=3)),
                ('ID_racer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racer.racer')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='ID_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racer.round'),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('commentator', models.CharField(max_length=50)),
                ('ID_Match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racer.match')),
            ],
        ),
    ]
