# Generated by Django 3.1.1 on 2021-01-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0003_result_time_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time_cost',
            field=models.TimeField(),
        ),
    ]
