# Generated by Django 3.1.1 on 2020-09-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('specific_information', models.CharField(blank=True, max_length=200, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='educational_background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.CharField(blank=True, max_length=200, null=True)),
                ('paper', models.CharField(blank=True, max_length=200, null=True)),
                ('achievement', models.CharField(blank=True, max_length=200, null=True)),
                ('tutor', models.CharField(blank=True, max_length=200, null=True)),
                ('University', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'educational backgroun',
            },
        ),
        migrations.CreateModel(
            name='interpersonal_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_members', models.CharField(blank=True, max_length=200, null=True)),
                ('friends', models.CharField(blank=True, max_length=200, null=True)),
                ('colleague', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'interpersonal relationship',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('bir', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
